Repository Sylius/RbacPlugin, pull requests merged in 2019-01, with the labels that each got.

#43 Mention other installation commands in README
  README.md
Labels: Maintenance

#46 Adding French translation
  src/Resources/translations/flashes.fr.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/translations/validators.fr.yml
Labels: enhancement

#44 Making README.md file great again
  README.md
Labels: Maintenance

#47 Decrease remove menu listener priority
  src/Resources/config/services.xml
Labels: Enhancement
